baseURL = 'https://zzhaolei.github.io/'
languageCode = 'zh'
defaultContentLanguage = 'zh'
title = 'Lei 的博客'
theme = 'PaperMod'

[params]
comments = true
dateFormat = "2006-01-02"
ShowToc = true
ShowShareButtons = false
ShowReadingTime = true
ShowBreadCrumbs = false
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true

[params.meta]
favicon = false

[params.homeInfoParams]
Title = "Lei 的博客"
Content = "(ง•_•)ง"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/zzhaolei"

# [[params.socialIcons]]
# name = "OldBlog"
# url = "https://www.cnblogs.com/zzhaolei"

[params.fuseOpts]
includeMatches = true
keys = ["title", "permalink", "summary", "content"]

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = false

[markup.highlight]
tabWidth = 4
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
style = "catppuccin-mocha"
